import { docUrl, type Constraint, type ModelDefinition, type ParamDef } from './types.ts'

/**
 * Kling — 19 video models.
 * Transcribed from .claude/skills/kie-models/references/kling.md.
 *
 * Family-wide traps encoded below:
 *  - `duration` is a QUOTED STRING everywhere except Kling 3.0 Omni, where it is
 *    an INTEGER. Sending the wrong JSON type is a 422.
 *  - Page slugs differ from model slugs (`v25-...` in the URL, `v2-5-...` in the API).
 *  - Kling 2.6 models use a `kling-2.6/` prefix, not `kling/`.
 */

// ---------------------------------------------------------------- shared params

const durationString = (
  values: string[],
  fallback: string,
  required = false,
): ParamDef => ({
  key: 'duration',
  type: 'enum',
  label: 'Duration',
  describe: 'Length of the generated video in seconds. Sent as a string.',
  group: 'framing',
  required,
  enum: values,
  default: fallback,
})

const cfgScale: ParamDef = {
  key: 'cfg_scale',
  type: 'number',
  label: 'CFG scale',
  describe:
    'How closely the model sticks to the prompt. Higher follows the prompt harder; lower gives the model more freedom.',
  group: 'advanced',
  min: 0,
  max: 1,
  step: 0.1,
  default: 0.5,
}

const negativePrompt = (maxLength: number): ParamDef => ({
  key: 'negative_prompt',
  type: 'text',
  label: 'Negative prompt',
  describe: 'Elements to keep out of the generated video.',
  group: 'advanced',
  maxLength,
})

const prompt = (maxLength: number, required = true): ParamDef => ({
  key: 'prompt',
  type: 'text',
  label: 'Prompt',
  describe: 'Text description of the video to generate.',
  group: 'core',
  required,
  maxLength,
})

const imageUrl = (label: string, describe: string): ParamDef => ({
  key: 'image_url',
  type: 'url',
  label,
  describe,
  group: 'core',
  required: true,
  accept: ['image'],
})

const aspectRatio = (values: string[], fallback: string, required = false): ParamDef => ({
  key: 'aspect_ratio',
  type: 'enum',
  label: 'Aspect ratio',
  describe: 'Frame shape of the generated video.',
  group: 'framing',
  required,
  enum: values,
  default: fallback,
})

// Kling 3.0 Omni shares one shot/subject vocabulary across all four models.
const omniMultiPrompt: ParamDef = {
  key: 'multi_prompt',
  type: 'object[]',
  label: 'Shots',
  describe:
    'Per-shot descriptions. Required when Custom multi-shot is on; must be empty otherwise.',
  group: 'motion',
  minItems: 1,
  maxItems: 6,
  fields: [
    {
      key: 'prompt',
      type: 'text',
      label: 'Shot description',
      describe: 'What happens in this shot.',
      group: 'core',
      required: true,
      minLength: 1,
      maxLength: 512,
    },
    {
      key: 'duration',
      type: 'number',
      label: 'Shot duration',
      describe: 'Length of this shot in seconds.',
      group: 'core',
      required: true,
      min: 1,
      max: 15,
      step: 1,
    },
  ],
}

const omniElements = (describe: string, maxItems?: number): ParamDef => ({
  key: 'elements',
  type: 'object[]',
  label: 'Subjects',
  describe,
  group: 'advanced',
  maxItems,
  default: [],
  fields: [
    {
      key: 'name',
      type: 'string',
      label: 'Name',
      describe: 'Unique per request. Reference it in the prompt as @name.',
      group: 'core',
      required: true,
    },
    {
      key: 'description',
      type: 'string',
      label: 'Description',
      describe: 'What this subject is.',
      group: 'core',
      required: true,
    },
    {
      key: 'element_input_urls',
      type: 'url[]',
      label: 'Reference assets',
      describe:
        'Either 2-4 images or exactly 1 video — never mixed within one subject.',
      group: 'core',
      required: true,
      minItems: 1,
      maxItems: 4,
      accept: ['image', 'video'],
    },
    {
      key: 'element_input_audio_urls',
      type: 'url[]',
      label: 'Reference audio',
      describe: 'Optional voice reference, 5-30s.',
      group: 'audio',
      accept: ['audio'],
      default: [],
    },
    {
      key: 'start_time',
      type: 'number',
      label: 'Trim start (ms)',
      describe: 'Start of the clip to use from a video subject.',
      group: 'advanced',
      default: 0,
    },
    {
      key: 'end_time',
      type: 'number',
      label: 'Trim end (ms)',
      describe: 'End of the clip. The span must be 3000-8000ms.',
      group: 'advanced',
      default: 8000,
    },
  ],
})

const omniResolution: ParamDef = {
  key: 'resolution',
  type: 'enum',
  label: 'Resolution',
  describe: 'Output resolution tier.',
  group: 'framing',
  enum: ['720p', '1080p', '4k'],
  default: '720p',
}

const omniDuration: ParamDef = {
  key: 'duration',
  type: 'number',
  label: 'Duration',
  describe: 'Total video length in seconds. An integer on Omni, unlike other Kling models.',
  group: 'framing',
  min: 3,
  max: 15,
  step: 1,
  default: 5,
}

const customizeMultiShots = (fallback?: boolean): ParamDef => ({
  key: 'customize_multi_shots',
  type: 'boolean',
  label: 'Custom multi-shot',
  describe: 'Define each shot yourself via Shots.',
  group: 'motion',
  ...(fallback === undefined ? {} : { default: fallback }),
})

const preferMultiShots: ParamDef = {
  key: 'prefer_multi_shots',
  type: 'boolean',
  label: 'Auto multi-shot',
  describe: 'Let the model plan shots. Cannot be combined with Custom multi-shot.',
  group: 'motion',
}

const audioToggle = (fallback?: boolean): ParamDef => ({
  key: 'audio',
  type: 'boolean',
  label: 'Audio',
  describe: 'Generate an audio track with the video.',
  group: 'audio',
  ...(fallback === undefined ? {} : { default: fallback }),
})

const OMNI_SHOT_CONSTRAINTS: Constraint[] = [
  {
    kind: 'mutuallyExclusive',
    keys: ['customize_multi_shots', 'prefer_multi_shots'],
    message:
      'Custom multi-shot and Auto multi-shot cannot both be on. Turn one off — both may be off.',
  },
  {
    kind: 'requiredWhen',
    keys: ['multi_prompt'],
    when: { key: 'customize_multi_shots', equals: true },
    message: 'Custom multi-shot needs at least one shot defined.',
  },
  {
    kind: 'forbiddenWhen',
    keys: ['multi_prompt'],
    when: { key: 'customize_multi_shots', equals: false },
    message: 'Shots only apply when Custom multi-shot is on.',
  },
]

// ---------------------------------------------------------------------- models

export const KLING_MODELS: ModelDefinition[] = [
  {
    slug: 'kling-2.6/text-to-video',
    family: 'kling',
    capability: 'text-to-video',
    label: 'Kling 2.6 — Text to Video',
    docUrl: docUrl('kling/text-to-video'),
    outputKind: 'video',
    params: [
      prompt(1000),
      {
        key: 'sound',
        type: 'boolean',
        label: 'Sound',
        describe: 'Whether the generated video contains sound.',
        group: 'audio',
        required: true,
      },
      aspectRatio(['1:1', '16:9', '9:16'], '1:1', true),
      durationString(['5', '10'], '5', true),
    ],
  },
  {
    slug: 'kling-2.6/image-to-video',
    family: 'kling',
    capability: 'image-to-video',
    label: 'Kling 2.6 — Image to Video',
    docUrl: docUrl('kling/image-to-video'),
    outputKind: 'video',
    params: [
      prompt(1000),
      {
        key: 'image_urls',
        type: 'url[]',
        label: 'Source image',
        describe: 'jpeg or png, up to 10MB. Exactly one image, sent as an array.',
        group: 'core',
        required: true,
        minItems: 1,
        maxItems: 1,
        accept: ['image'],
      },
      {
        key: 'sound',
        type: 'boolean',
        label: 'Sound',
        describe: 'Whether the generated video contains sound.',
        group: 'audio',
        required: true,
      },
      durationString(['5', '10'], '5', true),
    ],
    notes: 'image_urls is an array capped at one item — an API quirk, not a mistake.',
  },
  {
    slug: 'kling/v2-5-turbo-text-to-video-pro',
    family: 'kling',
    capability: 'text-to-video',
    label: 'Kling 2.5 Turbo Pro — Text to Video',
    docUrl: docUrl('kling/v25-turbo-text-to-video-pro'),
    outputKind: 'video',
    params: [
      prompt(2500),
      durationString(['5', '10'], '5'),
      aspectRatio(['16:9', '9:16', '1:1'], '16:9'),
      negativePrompt(2500),
      cfgScale,
    ],
  },
  {
    slug: 'kling/v2-5-turbo-image-to-video-pro',
    family: 'kling',
    capability: 'image-to-video',
    label: 'Kling 2.5 Turbo Pro — Image to Video',
    docUrl: docUrl('kling/v25-turbo-image-to-video-pro'),
    outputKind: 'video',
    params: [
      prompt(2500),
      imageUrl('First frame', 'jpeg or png, up to 10MB.'),
      {
        key: 'tail_image_url',
        type: 'url',
        label: 'Last frame',
        describe: 'Optional tail frame. jpeg or png, up to 10MB.',
        group: 'core',
        accept: ['image'],
      },
      durationString(['5', '10'], '5'),
      negativePrompt(500),
      cfgScale,
    ],
  },
  {
    slug: 'kling/v2-1-master-text-to-video',
    family: 'kling',
    capability: 'text-to-video',
    label: 'Kling 2.1 Master — Text to Video',
    docUrl: docUrl('kling/v2-1-master-text-to-video'),
    outputKind: 'video',
    params: [
      prompt(5000),
      durationString(['5', '10'], '5'),
      aspectRatio(['16:9', '9:16', '1:1'], '16:9'),
      negativePrompt(500),
      cfgScale,
    ],
  },
  {
    slug: 'kling/v2-1-master-image-to-video',
    family: 'kling',
    capability: 'image-to-video',
    label: 'Kling 2.1 Master — Image to Video',
    docUrl: docUrl('kling/v2-1-master-image-to-video'),
    outputKind: 'video',
    params: [
      prompt(5000),
      imageUrl('Source image', 'jpeg or png, up to 10MB.'),
      durationString(['5', '10'], '5'),
      negativePrompt(500),
      cfgScale,
    ],
  },
  {
    slug: 'kling/v2-1-pro',
    family: 'kling',
    capability: 'image-to-video',
    label: 'Kling 2.1 Pro — Image to Video',
    docUrl: docUrl('kling/v2-1-pro'),
    outputKind: 'video',
    params: [
      prompt(5000),
      imageUrl('First frame', 'jpeg or png, up to 10MB.'),
      {
        key: 'tail_image_url',
        type: 'url',
        label: 'Last frame',
        describe: 'Optional end frame. jpeg or png, up to 10MB.',
        group: 'core',
        accept: ['image'],
      },
      durationString(['5', '10'], '5'),
      negativePrompt(500),
      cfgScale,
    ],
  },
  {
    slug: 'kling/v2-1-standard',
    family: 'kling',
    capability: 'image-to-video',
    label: 'Kling 2.1 Standard — Image to Video',
    docUrl: docUrl('kling/v2-1-standard'),
    outputKind: 'video',
    params: [
      prompt(5000),
      imageUrl('Source image', 'jpeg or png, up to 10MB.'),
      durationString(['5', '10'], '5'),
      negativePrompt(500),
      cfgScale,
    ],
  },
  {
    slug: 'kling/ai-avatar-standard',
    family: 'kling',
    capability: 'avatar',
    label: 'Kling AI Avatar — Standard',
    docUrl: docUrl('kling/ai-avatar-standard'),
    outputKind: 'video',
    params: [
      imageUrl('Avatar image', 'The face to animate. jpeg or png, up to 10MB.'),
      {
        key: 'audio_url',
        type: 'url',
        label: 'Audio',
        describe:
          'Speech to lip-sync to. mpeg, wav, x-wav, aac, mp4 or ogg. Up to 100MB and 5 minutes.',
        group: 'core',
        required: true,
        accept: ['audio'],
      },
      prompt(5000),
    ],
  },
  {
    slug: 'kling/ai-avatar-pro',
    family: 'kling',
    capability: 'avatar',
    label: 'Kling AI Avatar — Pro',
    docUrl: docUrl('kling/ai-avatar-pro'),
    outputKind: 'video',
    params: [
      imageUrl('Avatar image', 'The face to animate. jpeg or png, up to 10MB.'),
      {
        key: 'audio_url',
        type: 'url',
        label: 'Audio',
        describe:
          'Speech to lip-sync to. mpeg, wav, x-wav, aac, mp4 or ogg. Up to 100MB and 5 minutes.',
        group: 'core',
        required: true,
        accept: ['audio'],
      },
      prompt(5000),
    ],
    notes: 'Identical inputs to ai-avatar-standard; the slug alone selects the quality tier.',
  },
  {
    slug: 'kling-2.6/motion-control',
    family: 'kling',
    capability: 'motion-control',
    label: 'Kling 2.6 — Motion Control',
    docUrl: docUrl('kling/motion-control'),
    outputKind: 'video',
    params: [
      prompt(2500, false),
      {
        key: 'input_urls',
        type: 'url[]',
        label: 'Subject image',
        describe:
          "Head, shoulders and torso must be visible. jpeg/png/jpg, up to 10MB, over 300px, aspect 2:5 to 5:2.",
        group: 'core',
        required: true,
        minItems: 1,
        maxItems: 1,
        accept: ['image'],
      },
      {
        key: 'video_urls',
        type: 'url[]',
        label: 'Driving video',
        describe: 'The motion to transfer. mp4 or quicktime, up to 100MB, 3-30 seconds.',
        group: 'core',
        required: true,
        minItems: 1,
        maxItems: 1,
        accept: ['video'],
      },
      {
        key: 'character_orientation',
        type: 'enum',
        label: 'Character orientation',
        describe:
          'image: match the still, output capped at 10s. video: match the driving video, up to 30s.',
        group: 'motion',
        required: true,
        enum: ['image', 'video'],
        default: 'video',
      },
      {
        key: 'mode',
        type: 'enum',
        label: 'Quality mode',
        describe: 'Output resolution tier.',
        group: 'framing',
        required: true,
        enum: ['720p', '1080p'],
        default: '720p',
      },
    ],
    notes:
      'DOC CONFLICT on `mode`: the OpenAPI enum lists 720p/1080p but the field description says to use std/pro. The sibling kling-3.0/motion-control uses std/pro. The enum is treated as authoritative until a live call settles it.',
  },
  {
    slug: 'kling-3.0/motion-control',
    family: 'kling',
    capability: 'motion-control',
    label: 'Kling 3.0 — Motion Control',
    docUrl: docUrl('kling/motion-control-v3'),
    outputKind: 'video',
    params: [
      {
        key: 'prompt',
        type: 'text',
        label: 'Prompt',
        describe: 'Guides the generated animation.',
        group: 'core',
        minLength: 0,
        maxLength: 2500,
      },
      {
        key: 'input_urls',
        type: 'url[]',
        label: 'Subject image',
        describe: 'One image URL.',
        group: 'core',
        required: true,
        minItems: 1,
        accept: ['image'],
      },
      {
        key: 'video_urls',
        type: 'url[]',
        label: 'Driving video',
        describe: 'One video URL.',
        group: 'core',
        required: true,
        minItems: 1,
        accept: ['video'],
      },
      {
        key: 'mode',
        type: 'enum',
        label: 'Quality mode',
        describe: 'std is 720p, pro is 1080p.',
        group: 'framing',
        enum: ['std', 'pro'],
      },
      {
        key: 'character_orientation',
        type: 'enum',
        label: 'Character orientation',
        describe: 'Which input decides which way the character faces. video is recommended.',
        group: 'motion',
        enum: ['video', 'image'],
        default: 'video',
      },
      {
        key: 'background_source',
        type: 'enum',
        label: 'Background source',
        describe: 'Take the background from the driving video or the subject image.',
        group: 'framing',
        enum: ['input_video', 'input_image'],
        default: 'input_video',
      },
    ],
  },
  {
    slug: 'kling-3.0/video',
    family: 'kling',
    capability: 'text-to-video',
    alsoSupports: ['image-to-video'],
    label: 'Kling 3.0 — Video',
    docUrl: docUrl('kling/kling-3-0'),
    outputKind: 'video',
    params: [
      {
        key: 'prompt',
        type: 'text',
        label: 'Prompt',
        describe: 'Used when multi-shot is off.',
        group: 'core',
      },
      {
        key: 'image_urls',
        type: 'url[]',
        label: 'Frames',
        describe:
          'One image is the first frame; two are first and last. Multi-shot supports the first frame only. Required when elements are referenced.',
        group: 'core',
        maxItems: 2,
        accept: ['image'],
      },
      {
        key: 'sound',
        type: 'boolean',
        label: 'Sound effects',
        describe: 'Defaults to on in multi-shot mode.',
        group: 'audio',
        default: false,
      },
      durationString(
        ['3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'],
        '5',
      ),
      aspectRatio(['16:9', '9:16', '1:1'], '16:9'),
      {
        key: 'mode',
        type: 'enum',
        label: 'Quality mode',
        describe: 'Generation tier, which also sets output resolution.',
        group: 'framing',
        enum: ['std', 'pro', '4K'],
        default: 'pro',
      },
      {
        key: 'multi_shots',
        type: 'boolean',
        label: 'Multi-shot',
        describe: 'Compose the video from several described shots.',
        group: 'motion',
        default: false,
      },
      {
        key: 'multi_prompt',
        type: 'object[]',
        label: 'Shots',
        describe: 'Up to 5 shots. Applies when Multi-shot is on.',
        group: 'motion',
        maxItems: 5,
        fields: [
          {
            key: 'prompt',
            type: 'text',
            label: 'Shot description',
            describe: 'Each @element reference consumes 37 of the 500 characters.',
            group: 'core',
            required: true,
            maxLength: 500,
          },
          {
            key: 'duration',
            type: 'number',
            label: 'Shot duration',
            describe: 'Seconds.',
            group: 'core',
            required: true,
            min: 1,
            max: 12,
            step: 1,
          },
        ],
      },
      {
        key: 'kling_elements',
        type: 'object[]',
        label: 'Elements',
        describe: 'Named subjects you can cite in the prompt as @name.',
        group: 'advanced',
        maxItems: 3,
        fields: [
          {
            key: 'name',
            type: 'string',
            label: 'Name',
            describe: 'Referenced in the prompt as @name.',
            group: 'core',
            required: true,
          },
          {
            key: 'description',
            type: 'string',
            label: 'Description',
            describe: 'What this element is.',
            group: 'core',
            required: true,
          },
          {
            key: 'element_input_urls',
            type: 'url[]',
            label: 'Reference assets',
            describe:
              'Either 2-4 images (jpg/png, 10MB each) or exactly 1 video (mp4/mov, 3-8s effective).',
            group: 'core',
            required: true,
            minItems: 1,
            maxItems: 4,
            accept: ['image', 'video'],
          },
          {
            key: 'element_input_audio_urls',
            type: 'url[]',
            label: 'Reference audio',
            describe: '5-30 seconds.',
            group: 'audio',
            accept: ['audio'],
          },
          {
            key: 'start_time',
            type: 'number',
            label: 'Trim start (ms)',
            describe: 'Start of the video segment to use.',
            group: 'advanced',
            default: 0,
          },
          {
            key: 'end_time',
            type: 'number',
            label: 'Trim end (ms)',
            describe: 'End of the segment. The span must be 3000-8000ms.',
            group: 'advanced',
          },
        ],
      },
    ],
    constraints: [
      {
        kind: 'requiredWhen',
        keys: ['multi_prompt'],
        when: { key: 'multi_shots', equals: true },
        message: 'Multi-shot needs at least one shot defined.',
      },
      {
        kind: 'requiredWhen',
        keys: ['prompt'],
        when: { key: 'multi_shots', equals: false },
        message: 'Single-shot mode needs a prompt.',
      },
    ],
  },
  {
    slug: 'kling/v3-turbo-text-to-video',
    family: 'kling',
    capability: 'text-to-video',
    label: 'Kling v3 Turbo — Text to Video',
    docUrl: docUrl('kling/v3-turbo-text-to-video'),
    outputKind: 'video',
    params: [
      prompt(2500),
      {
        key: 'duration',
        type: 'string',
        label: 'Duration',
        describe: 'Seconds, from 3 to 15. Sent as a string.',
        group: 'framing',
        required: true,
        default: '5',
      },
      aspectRatio(['1:1', '9:16', '16:9'], '16:9', true),
      {
        key: 'resolution',
        type: 'enum',
        label: 'Resolution',
        describe: 'Output resolution tier.',
        group: 'framing',
        required: true,
        enum: ['720p', '1080p'],
        default: '720p',
      },
    ],
    notes:
      'The doc states duration as a 3-15s range without enumerating the accepted values, so this is a free string rather than an invented enum.',
  },
  {
    slug: 'kling/v3-turbo-image-to-video',
    family: 'kling',
    capability: 'image-to-video',
    label: 'Kling v3 Turbo — Image to Video',
    docUrl: docUrl('kling/v3-turbo-image-to-video'),
    outputKind: 'video',
    params: [
      prompt(2500),
      {
        key: 'image_urls',
        type: 'url[]',
        label: 'Source image',
        describe: 'jpeg or png, up to 10MB.',
        group: 'core',
        required: true,
        minItems: 1,
        accept: ['image'],
      },
      {
        key: 'duration',
        type: 'string',
        label: 'Duration',
        describe: 'Seconds, from 3 to 15. Sent as a string.',
        group: 'framing',
        required: true,
        default: '5',
      },
      {
        key: 'resolution',
        type: 'enum',
        label: 'Resolution',
        describe: 'Output resolution tier.',
        group: 'framing',
        required: true,
        enum: ['720p', '1080p'],
        default: '720p',
      },
    ],
    notes:
      'No aspect_ratio — framing follows the input image. Duration is a free string for the same reason as v3-turbo-text-to-video.',
  },
  {
    slug: 'kling-3.0-omni/text-to-video',
    family: 'kling',
    capability: 'text-to-video',
    label: 'Kling 3.0 Omni — Text to Video',
    docUrl: docUrl('kling/v3-omni-text-to-video'),
    outputKind: 'video',
    params: [
      {
        key: 'prompt',
        type: 'text',
        label: 'Prompt',
        describe: 'Must not be empty after trimming whitespace.',
        group: 'core',
        required: true,
        minLength: 1,
        maxLength: 3072,
      },
      customizeMultiShots(true),
      preferMultiShots,
      omniMultiPrompt,
      omniElements('Up to 7 multi-image subjects, or up to 3 video-character subjects.'),
      audioToggle(false),
      omniResolution,
      aspectRatio(['16:9', '9:16', '1:1'], '16:9'),
      omniDuration,
    ],
    constraints: OMNI_SHOT_CONSTRAINTS,
  },
  {
    slug: 'kling-3.0-omni/image-to-video',
    family: 'kling',
    capability: 'image-to-video',
    label: 'Kling 3.0 Omni — Image to Video',
    docUrl: docUrl('kling/v3-omni-image-to-video'),
    outputKind: 'video',
    params: [
      {
        key: 'prompt',
        type: 'text',
        label: 'Prompt',
        describe: 'Must not be empty after trimming whitespace.',
        group: 'core',
        required: true,
        maxLength: 3072,
      },
      {
        key: 'image_urls',
        type: 'url[]',
        label: 'Frames',
        describe:
          'One image is the first frame; two are first and last. jpg/jpeg/png, up to 50MB, at least 300px, aspect 0.4-2.5.',
        group: 'core',
        required: true,
        minItems: 1,
        maxItems: 2,
        accept: ['image'],
      },
      omniDuration,
      omniResolution,
      {
        key: 'aspect_ratio',
        type: 'enum',
        label: 'Aspect ratio',
        describe:
          'Explicit ratios are selectable only with Custom multi-shot on; otherwise use auto.',
        group: 'framing',
        enum: ['16:9', '9:16', '1:1', 'auto'],
        default: 'auto',
      },
      audioToggle(),
      customizeMultiShots(false),
      preferMultiShots,
      omniMultiPrompt,
      omniElements('Up to 3 subjects.', 3),
    ],
    constraints: OMNI_SHOT_CONSTRAINTS,
  },
  {
    slug: 'kling-3.0-omni/reference-to-video',
    family: 'kling',
    capability: 'reference-to-video',
    label: 'Kling 3.0 Omni — Reference to Video',
    docUrl: docUrl('kling/v3-omni-reference-to-video'),
    outputKind: 'video',
    params: [
      {
        key: 'prompt',
        type: 'text',
        label: 'Prompt',
        describe: 'Must not be empty after trimming whitespace.',
        group: 'core',
        required: true,
        maxLength: 3072,
      },
      {
        key: 'image_urls',
        type: 'url[]',
        label: 'Reference images',
        describe: 'jpg/jpeg/png, up to 50MB each, at least 300px, aspect 0.4-2.5.',
        group: 'core',
        maxItems: 7,
        accept: ['image'],
      },
      {
        key: 'video_urls',
        type: 'url[]',
        label: 'Reference video',
        describe:
          'Exactly one. mp4/mov, up to 200MB, 3-15.5s, 700-4553px, aspect 0.4-2, 24-60fps.',
        group: 'core',
        maxItems: 1,
        accept: ['video'],
      },
      omniDuration,
      omniResolution,
      {
        key: 'aspect_ratio',
        type: 'enum',
        label: 'Aspect ratio',
        describe:
          'auto is required with video-only input; explicit ratios apply without video or with both.',
        group: 'framing',
        enum: ['16:9', '9:16', '1:1', 'auto'],
        default: '16:9',
      },
      {
        key: 'audio',
        type: 'boolean',
        label: 'Audio',
        describe: 'Must be off when a reference video is supplied.',
        group: 'audio',
      },
      customizeMultiShots(),
      preferMultiShots,
      omniMultiPrompt,
      omniElements(
        'Subject limits vary by input: 7 combined without video, 4 with video, 1 for a video character.',
      ),
    ],
    constraints: [
      ...OMNI_SHOT_CONSTRAINTS,
      {
        kind: 'requiresOneOf',
        keys: ['image_urls', 'video_urls'],
        message: 'Provide reference images, a reference video, or both.',
      },
    ],
    notes:
      'Three valid scenarios: images only; video only (forces aspect_ratio auto and audio false); images plus video (forces audio false). Video-character subjects cannot combine with multi-image subjects or reference images.',
  },
  {
    slug: 'kling-3.0-omni/transformation',
    family: 'kling',
    capability: 'video-to-video',
    label: 'Kling 3.0 Omni — Transformation',
    docUrl: docUrl('kling/v3-omni-transformation'),
    outputKind: 'video',
    params: [
      {
        key: 'prompt',
        type: 'text',
        label: 'Prompt',
        describe: 'How to transform the source video.',
        group: 'core',
        required: true,
        minLength: 1,
        maxLength: 3072,
      },
      {
        key: 'video_urls',
        type: 'url[]',
        label: 'Source video',
        describe:
          'Exactly one. mp4/mov, up to 200MB, 3-15.5s, 700-4553px, aspect 0.4-2, 24-60fps.',
        group: 'core',
        required: true,
        minItems: 1,
        maxItems: 1,
        accept: ['video'],
      },
      {
        key: 'image_urls',
        type: 'url[]',
        label: 'Reference images',
        describe:
          'jpg/jpeg/png, up to 50MB, at least 300px, aspect 0.4-2.5. Four total including multi-image subjects.',
        group: 'core',
        maxItems: 4,
        accept: ['image'],
      },
      {
        key: 'duration',
        type: 'string',
        label: 'Duration',
        describe: 'Configurable only when using video together with images.',
        group: 'framing',
      },
      omniResolution,
      {
        key: 'aspect_ratio',
        type: 'enum',
        label: 'Aspect ratio',
        describe: 'auto is required for video-only input; explicit ratios need images too.',
        group: 'framing',
        enum: ['auto', '16:9', '9:16', '1:1'],
        default: '16:9',
      },
      audioToggle(),
      omniElements(
        'Up to 7 multi-image subjects, 3 video characters, or a 3+4 mix.',
        7,
      ),
    ],
    notes:
      'Video character subjects cannot be used together with multi-image subjects or reference images.',
  },
]
